# Test Installation and Setup of older versions of SQL Servers (2005)
---
platforms:
  - name: windows-2008r2
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2008r2

suites:
  - name: sqlserver2005sp4
    provisioner:
      manifest: sqlserver2005sp4_2_instances.pp
      custom_facts:
        sqlserver2005_iso_url: <%= ENV['SQLSERVER2005_ISO_URL'] %>
      max_retries: 4
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2005sp4_2_instances_spec.rb
