# Test installations of SSMS
---
platforms:
  - name: windows-2012r2
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2012r2
  - name: windows-2016
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2016
  - name: windows-10
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-10

suites:
  - name: localdbs
    provisioner:
      manifest: localdbs.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/localdbs_spec.rb
  - name: ssms2016
    provisioner:
      manifest: ssms2016.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/ssms2016_spec.rb
  - name: ssms2017
    excludes:
      - windows-2008r2
    provisioner:
      manifest: ssms2017.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/ssms2017_spec.rb
