---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  custom_options: <%= ENV['PUPPET_COLOR'] %>
  puppet_debug: <%= ENV['PUPPET_DEBUG'] %>
  manifests_path: spec/manifests
  modules_path: .kitchen-modules
  require_chef_for_busser: false
  resolve_with_librarian_puppet: false
  puppet_detailed_exitcodes: true
  require_puppet_collections: true
  puppet_detailed_exitcodes: true
  max_retries: 2
  wait_for_retry: 30
  retry_on_exit_code:
    - 2 # The run succeeded, and some resources were changed.
    - 6 # The run succeeded, and included both changes and failures.

transport:
  name: winrm
  elevated: true

platforms:
  - name: windows-2012r2
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2012r2

verifier:
  name: shell

suites:
  - name: ssms2016
    provisioner:
      manifest: ssms2016.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/ssms2016_spec.rb
  - name: localdbs
    provisioner:
      manifest: localdbs.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/localdbs_spec.rb
  - name: sqlserver2012sp3
    provisioner:
      manifest: sqlserver2012sp3_2_instances.pp
      custom_facts:
        sqlserver2012_iso_url: <%= ENV['SQLSERVER2012_ISO_URL'] %>
      max_retries: 4
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2012sp3_2_instances_spec.rb
  - name: sqlserver2016rtm
    provisioner:
      manifest: sqlserver2016rtm.pp
      custom_facts:
        sqlserver2016_iso_url: <%= ENV['SQLSERVER2016_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2016rtm_spec.rb
  - name: sqlserver2016sp1
    provisioner:
      manifest: sqlserver2016sp1_2_instances.pp
      custom_facts:
        sqlserver2016_iso_url: <%= ENV['SQLSERVER2016_ISO_URL'] %>
      max_retries: 4
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2016sp1_2_instances_spec.rb
  - name: sqlserver2014rtm
    provisioner:
      manifest: sqlserver2014rtm.pp
      custom_facts:
        sqlserver2014_iso_url: <%= ENV['SQLSERVER2014_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2014rtm_spec.rb
  - name: sqlserver2014sp2
    provisioner:
      manifest: sqlserver2014sp2_2_instances.pp
      custom_facts:
        sqlserver2014_iso_url: <%= ENV['SQLSERVER2014_ISO_URL'] %>
      max_retries: 4
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2014sp2_2_instances_spec.rb
  - name: sqlserver2017ctp
    provisioner:
      manifest: sqlserver2017ctp.pp
      custom_facts:
        sqlserver2017_iso_url: <%= ENV['SQLSERVER2017_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2017ctp_spec.rb
  - name: sqlserver2017ctpmultiple
    provisioner:
      manifest: sqlserver2017ctp_2_instances.pp
      custom_facts:
        sqlserver2017_iso_url: <%= ENV['SQLSERVER2017_ISO_URL'] %>
      max_retries: 4
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2017ctp_2_instances_spec.rb
  - name: ssms2017
    provisioner:
      manifest: ssms2017.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/ssms2017_spec.rb
